### ISSUE TITLE
开始菜单没有汉化翻译

### ISSUE THREAD

**Issue by OSac1822O** [zetaloop/ExplorerPatcher#26]
如题，即使安装了(包括手动覆盖)补充汉化的内容还是没有开始菜单汉化
![屏幕截图 2023-07-12 163915](https://github.com/zetaloop/ExplorerPatcher/assets/54127849/88e1e42b-609f-44b9-9724-b384813503f0)
![屏幕截图 2023-07-12 163900](https://github.com/zetaloop/ExplorerPatcher/assets/54127849/22b56417-b77b-47bc-86a3-09aafcc37945)

**Comment by OSac1822O** [comment]
> 如题，即使安装了(包括手动覆盖)补充汉化的内容还是没有开始菜单汉化 ![屏幕截图 2023-07-12 163915](https://user-images.githubusercontent.com/54127849/252909555-88e1e42b-609f-44b9-9724-b384813503f0.png) ![屏幕截图 2023-07-12 163900](https://user-images.githubusercontent.com/54127849/252909577-22b56417-b77b-47bc-86a3-09aafcc37945.png)

![屏幕截图 2023-07-12 164049](https://github.com/zetaloop/ExplorerPatcher/assets/54127849/a0e93339-109b-45c7-b42c-0a87b121cc90)
![屏幕截图 2023-07-12 164108](https://github.com/zetaloop/ExplorerPatcher/assets/54127849/b8e89ba7-b68c-4f67-bc28-fb94c1df1842)

**Comment by zetaloop** [comment]
我可能发现是什么原因了，正在尝试汉化新的Windows.UI.ShellCommon.en-US.pri

**Comment by zetaloop** [comment]
实现了，感谢来自 [bbmaster123/10SM](https://github.com/bbmaster123/10SM) 项目的原版中文资源文件，我正在更新这个开始菜单汉化包

**Comment by zetaloop** [comment]
请试一下这个：[补充汉化v2.0.zip](https://github.com/zetaloop/ExplorerPatcher/files/12028650/v2.0.zip)

**Comment by OSac1822O** [comment]
> 请试一下这个：[补充汉化v2.0.zip](https://github.com/zetaloop/ExplorerPatcher/files/12028650/v2.0.zip)

非常感谢,这个问题终于解决了!
