### ISSUE TITLE
请问怎么像win10一样把照片放到开始菜单里呢？

### ISSUE THREAD

**Issue by n4y22** [zetaloop/ExplorerPatcher#30]
您好，我想知道怎么样才能像win10一样把图片磁贴放到开始菜单里。感谢您的解答。

**Comment by zetaloop** [comment]
我试了一下，由于win11“固定到开始菜单”api不再兼容win10开始菜单，现无法自定义磁贴了。

**Comment by zetaloop** [comment]
请试试 [TileIconifier](https://github.com/Jonno12345/TileIconifier)，在 https://github.com/valinet/ExplorerPatcher/discussions/1679 中提到可能可以自定义磁贴。
