### ISSUE TITLE
22621.1992.56.1 Translation 19 这个版本没法用

### ISSUE THREAD

**Issue by Ext2RO** [zetaloop/ExplorerPatcher#32]
如题，开始菜单打不开，请问有没有破解之法？

**Comment by zetaloop** [comment]
请问你是哪个系统版本？以前ep可以使用吗？最近是否更新了系统？

**Comment by Ext2RO** [comment]
你好，一直都在用ep，由于ep没有发布新版本，虽然Windows一直提醒更新但都没敢更新，这前两天看到 ep 发布新版本了，才敢更新的 Windows，看到更新列表中有 KB5028185，更新完之后看了一下系统版本，是22621.1992，也符合这次 ep 的新版本号，安装了之后任务栏正常，能显示不合并的图标，但开始菜单打不开，点击没有反应，在任务栏上点右键选“任务栏设置”也会导致资源管理器重启。

**Comment by Ext2RO** [comment]
电脑重启之后，又提示一个更新 KB5028254，我没有更新这个，暂停更新了。

**Comment by Ext2RO** [comment]
卸载了 KB5028185 这个更新，目前系统版本是 22621.1265，可以正常使用了。

**Comment by zetaloop** [comment]
> 你好，一直都在用ep，由于ep没有发布新版本，虽然Windows一直提醒更新但都没敢更新，这前两天看到 ep 发布新版本了，才敢更新的 Windows，看到更新列表中有 KB5028185，更新完之后看了一下系统版本，是22621.1992，也符合这次 ep 的新版本号，安装了之后任务栏正常，能显示不合并的图标，但开始菜单打不开，点击没有反应，在任务栏上点右键选“任务栏设置”也会导致资源管理器重启。

EP 把开始菜单和任务栏右键菜单整坏也不是一次两次了😂
我这里是 Beta 22631.2115，用 win10 开始菜单+win10 任务栏的时候很稳，但是混搭可能出问题。
如果你用 win11 任务栏出现右键闪退问题，去属性-高级-不修改任务栏右键菜单 打开，也许可以修复。

**Comment by Ext2RO** [comment]
好的，我试一下，谢谢了 😄🤝
