### ISSUE TITLE
感谢翻译，请问没有汉化是不是因为我的系统太老了？

### ISSUE THREAD

**Issue by zxrone** [zetaloop/ExplorerPatcher#37]
thank u for your answer
![2023-08-19_133627](https://github.com/zetaloop/ExplorerPatcher/assets/72288735/d7b4f30e-0477-4e65-a77a-5fc6042ebd36)

**Comment by zetaloop** [comment]
你是使用win10吗

**Comment by zetaloop** [comment]
win10的界面可能是还没汉化的，当时没考虑到还有win10用户来用，要不你等我过会儿补一下

**Comment by zxrone** [comment]
> win10的界面可能是还没汉化的，当时没考虑到还有win10用户来用，要不你等我过会儿补一下

非常感谢

**Comment by zetaloop** [comment]
你好，做好了（最新的 Pre-release），可以试试嘛？
