### ISSUE TITLE
byd打开直接给我任务管理器崩了

### ISSUE THREAD

**Issue by xynsf** [zetaloop/ExplorerPatcher#46]
现在桌面是白的，就打开这几个窗口还在，在线等挺急的

**Comment by zetaloop** [comment]
6，你是哪个系统版本？可能是版本差太远了不兼容。另外，官方汉化已经有了，推荐直接用官方版。

抢救方法：打开cmd，del C:\Windows\dxgi.dll 即可卸载EP

**Comment by xynsf** [comment]
实际情况是：我的资源管理器重启太慢了导致我有一种崩溃了的感觉·····

**Comment by xynsf** [comment]
半个小时后自己好了

**Comment by xynsf** [comment]
然后我又手欠点了重启任务资源管理器····

**Comment by xynsf** [comment]
> 6，你是哪个系统版本？可能是版本差太远了不兼容。另外，官方汉化已经有了，推荐直接用官方版。
> 
> 抢救方法：打开cmd，del C:\Windows\dxgi.dll 即可卸载EP

啊对了，win+r打开的cmd没权限删除，手动删除显示被任务管理器占用，只能用杀毒软件的文件粉碎
