### ISSUE TITLE
怎么删除程序啊?

### ISSUE THREAD

**Issue by LiuX137114** [zetaloop/ExplorerPatcher#48]
我只想改变win菜单

**Comment by zetaloop** [comment]
如果需要卸载EP，你可以选一种卸载方式：

1. 把安装包ep_setup.exe重命名为ep_uninstall.exe然后运行来卸载

2. 在系统设置里卸载ExplorerPatcher软件

3. 直接删除C:\Windows\dxgi.dll文件

**Comment by LiuX137114** [comment]
谢谢你
